Sundsvallskommun/api-service-messaging

README.md, src/main/java/se/sundsvall/messaging/integration/emailsender/EmailProcessor.java, src/main/java/se/sundsvall/messaging/integration/smssender/SmsProcessor.java, src/main/java/se/sundsvall/messaging/integration/smssender/SmsSenderIntegrationMapper.java, src/main/java/se/sundsvall/messaging/processor/MessageProcessor.java, src/test/java/se/sundsvall/messaging/integration/emailsender/EmailProcessorTests.java, src/test/java/se/sundsvall/messaging/integration/smssender/SmsProcessorTests.java
Fixed missing subject mapping for e-mail. Also corrected handling of default sender for e-mails and SMS:es.
=> Bugfix for subject mapping

src/integration-test/java/openapi/OpenApiSpecificationIT.java, src/integration-test/resources/MessagesIT/__files/test1_successfulRequest_bySms/responses/sms-sender.json, src/integration-test/resources/SmsIT/__files/test1_successfulRequest/responses/sms-sender.json, src/main/java/se/sundsvall/messaging/api/MessageResource.java, src/main/java/se/sundsvall/messaging/api/model/Request.java, src/main/java/se/sundsvall/messaging/api/model/validation/ValidHeaderNameConstraintValidator.java, src/main/java/se/sundsvall/messaging/integration/feedbacksettings/FeedbackSettingsIntegrationConfiguration.java, src/main/java/se/sundsvall/messaging/integration/smssender/SmsProcessor.java, src/main/java/se/sundsvall/messaging/integration/smssender/SmsSenderClient.java, src/main/java/se/sundsvall/messaging/integration/smssender/SmsSenderIntegration.java, src/main/java/se/sundsvall/messaging/integration/smssender/SmsSenderIntegrationConfiguration.java, src/main/resources/openapi.yaml, src/test/java/se/sundsvall/messaging/TestDataFactory.java, src/test/java/se/sundsvall/messaging/api/model/SmsRequestTests.java, src/test/java/se/sundsvall/messaging/integration/smssender/SmsProcessorTests.java, src/test/java/se/sundsvall/messaging/integration/smssender/SmsSenderIntegrationTests.java, src/test/java/se/sundsvall/messaging/model/HeaderTests.java, src/test/java/se/sundsvall/messaging/model/validation/HeaderValidationTests.java, src/test/java/se/sundsvall/messaging/processor/MessageProcessorTests.java
Changes to reflect the changes in the SmsSender API.
Also changes the SmsSender client to use Feign instead of RestTemplate.
=> UF-2674 - Clean up SmsSender

pom.xml, src/generated/web-message-sender-api.yml, src/integration-test/resources/WebMessageIT/__files/test1_successfulRequest/request.json, src/main/java/se/sundsvall/messaging/api/MessageResource.java, src/main/java/se/sundsvall/messaging/api/StatusAndHistoryResource.java, src/main/java/se/sundsvall/messaging/api/model/WebMessageRequest.java, src/main/java/se/sundsvall/messaging/dto/WebMessageDto.java, src/main/java/se/sundsvall/messaging/integration/webmessagesender/WebMessageProcessor.java, src/main/java/se/sundsvall/messaging/integration/webmessagesender/WebMessageSenderIntegrationMapper.java, src/main/resources/application.properties, src/main/resources/openapi.yml, src/test/java/se/sundsvall/messaging/TestDataFactory.java, src/test/java/se/sundsvall/messaging/integration/webmessagesender/WebMessageProcessorTests.java
Updates the `/webmessage` resource, adding support for sending attachments and bumps the API version to 2.3.
=> UF-3084 - Update /webmessage resource

src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/model/DigitalMailRequest.java, src/main/java/se/sundsvall/messaging/api/model/LetterRequest.java, src/main/java/se/sundsvall/messaging/processor/LetterProcessor.java, src/main/java/se/sundsvall/messaging/service/event/IncomingLetterEvent.java
Updates the OpenAPI description of the `body` with a clarification of how it's handled with regard to the `contentType`.
Also sneaks in a minor simplification of the letter processor.
=> UF-3589 - Update OpenAPI docs for /letter and /digital-mail

pom.xml
=> Develop -> main

src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/StatusAndHistoryResource.java, src/main/java/se/sundsvall/messaging/api/model/MessageStatusResponse.java
Adds message type to the response for various status endpoints. Also, corrects some OpenAPI response definitions for them.
=> UF-4510 - Add message type to status

pom.xml, src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/StatusAndHistoryResource.java, src/main/java/se/sundsvall/messaging/api/model/DigitalMailRequest.java, src/main/java/se/sundsvall/messaging/api/model/LetterRequest.java, src/main/java/se/sundsvall/messaging/api/model/MessageStatusResponse.java, src/main/java/se/sundsvall/messaging/api/model/SnailmailRequest.java, src/main/resources/application-default.properties
Adds constraints to ensure that attachments are provided to /letter.
Also bumps dept44 to 1.30
=> UF-4508 - Letter/snail-mail request validation

pom.xml, src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/model/BatchRequest.java, src/main/java/se/sundsvall/messaging/api/model/EmailRequest.java, src/main/java/se/sundsvall/messaging/api/model/MessageRequest.java, src/main/java/se/sundsvall/messaging/api/model/Request.java, src/main/java/se/sundsvall/messaging/api/model/SmsRequest.java, src/main/java/se/sundsvall/messaging/api/model/SnailmailRequest.java, src/main/java/se/sundsvall/messaging/api/model/WebMessageRequest.java, src/main/java/se/sundsvall/messaging/dto/WebMessageDto.java, src/main/java/se/sundsvall/messaging/integration/webmessagesender/WebMessageSenderIntegrationMapper.java, src/main/java/se/sundsvall/messaging/model/PartyWithOptionalPartyId.java, src/main/java/se/sundsvall/messaging/model/PartyWithRequiredPartyId.java, src/main/java/se/sundsvall/messaging/processor/MessageProcessor.java, src/main/java/se/sundsvall/messaging/service/mapper/MessageMapper.java, src/test/java/se/sundsvall/messaging/TestDataFactory.java, src/test/java/se/sundsvall/messaging/integration/webmessagesender/WebMessageSenderIntegrationMapperTests.java, src/test/java/se/sundsvall/messaging/model/validation/PartyValidationTests.java
Fixes some constraint validations that were either too permissive or too restrictive
Also, bumps dept44 to 1.31
=> UF-4612 - Validation constraint review

src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/model/request/EmailRequest.java, src/main/java/se/sundsvall/messaging/integration/db/DbIntegration.java, src/main/java/se/sundsvall/messaging/service/MessageService.java, src/test/java/se/sundsvall/messaging/api/model/response/MessageResultTests.java
Fixes an inconsistency in the /letter message grouping, in order to align better with the grouping in /message message grouping
=> UF-4884 - Inconsistent letter message grouping

src/main/java/se/sundsvall/messaging/model/InternalDeliveryResult.java, src/main/java/se/sundsvall/messaging/service/MessageEventDispatcher.java, src/main/java/se/sundsvall/messaging/service/MessageEventHandler.java, src/main/java/se/sundsvall/messaging/service/MessageService.java, src/main/resources/db/migration/V3.6__add_additional_history_indices.sql, src/test/java/se/sundsvall/messaging/service/MessageEventHandlerTests.java, src/test/java/se/sundsvall/messaging/service/MessageServiceTests.java
Fixes a bug with async letter delivery. Also, adds additional indices on the history table.
=> Letter async refactoring

src/main/java/se/sundsvall/messaging/service/MessageService.java, src/main/java/se/sundsvall/messaging/service/mapper/MessageMapper.java, src/main/java/se/sundsvall/messaging/service/mapper/RequestMapper.java, src/test/java/se/sundsvall/messaging/service/MessageServiceTests.java
Fixes a bug where deliveries sent using letter were incorrectly grouped
=> Bugfix - letter grouping

src/main/java/se/sundsvall/messaging/Application.java, src/main/java/se/sundsvall/messaging/api/MessageResource.java, src/main/java/se/sundsvall/messaging/configuration/BlacklistProperties.java, src/main/java/se/sundsvall/messaging/configuration/Defaults.java, src/main/java/se/sundsvall/messaging/service/mapper/RequestMapper.java, src/test/java/se/sundsvall/messaging/StartupHandlerTests.java, src/test/java/se/sundsvall/messaging/api/model/response/StatsResponseTests.java, src/test/java/se/sundsvall/messaging/integration/feedbacksettings/FeedbackSettingsIntegrationTests.java, src/test/java/se/sundsvall/messaging/model/HistoryTests.java, src/test/java/se/sundsvall/messaging/service/mapper/StatisticsMapperTests.java
=> UF-5597 - Messaging code smells

pom.xml, src/integration-test/resources/SmsIT/__files/test1_successfulRequest/request.json, src/integration-test/resources/SmsIT/__files/test2_internalServerErrorFromSmsSender/request.json, src/main/java/se/sundsvall/messaging/api/model/request/SmsRequest.java, src/main/resources/integrations/sms-sender-1.2.yml, src/test/java/se/sundsvall/messaging/TestDataFactory.java, src/test/java/se/sundsvall/messaging/api/model/request/SmsRequestConstraintValidationTests.java
Migrates mobile numbers to use MSISDN (+country code), to be able to send SMS to other countries than Sweden.
=> UF-5699 - MSISDN for SMS

pom.xml, src/main/resources/application.yml
Removes all v3 distinctions as part of the v2 decommision
=> UF-6358 - v2 decommission

src/main/resources/application-default.yml, src/main/resources/application.yml
- To enable environment independent logbook exclusion filtering, the setting has been moved to the application.yml
=> UF-6302: Moved filter setting to application.yml

src/main/java/se/sundsvall/messaging/integration/digitalmailsender/DigitalMailSenderIntegrationMapper.java, src/main/resources/integrations/digital-mail-sender-2.0.yml, src/test/java/se/sundsvall/messaging/integration/digitalmailsender/DigitalMailSenderIntegrationMapperTests.java
Fixes an error where messaging passed the wrong content-type to digital-mail
=> UF-6499 - Wrong digital-mail content-type

src/integration-test/resources/DigitalInvoiceIT/__files/test1_successfulRequest/mappings/digital-mail-sender.json, src/integration-test/resources/DigitalInvoiceIT/__files/test2_internalServerErrorFromDigitalMailSender/mappings/digital-mail-sender.json, src/main/java/se/sundsvall/messaging/integration/digitalmailsender/DigitalMailSenderClient.java
Fixes the digital-mail-sender endpoint URL for sending digital invoices
=> UF-6664 - Wrong endpoint for digital invoices

src/integration-test/resources/StatisticsIT/__files/test2_successfulDepartmentStats/response.json, src/main/java/se/sundsvall/messaging/service/mapper/StatisticsMapper.java, src/test/java/se/sundsvall/messaging/service/mapper/StatisticsMapperTest.java
=> UF-10461: Changed description for unknown departments

src/main/java/se/sundsvall/messaging/integration/db/DbIntegration.java, src/main/java/se/sundsvall/messaging/integration/db/MessageRepository.java, src/main/java/se/sundsvall/messaging/service/MessageService.java
Adds an additional check before triggering/submitting snailmail batches
=> UF-10674 - Snailmail batch trigger

src/main/java/se/sundsvall/messaging/service/MessageService.java, src/test/java/se/sundsvall/messaging/service/MessageServiceTest.java
=> UF-10944 - Fixed not sending snail-mail batches

pom.xml, src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/model/request/WebMessageRequest.java, src/test/java/se/sundsvall/messaging/api/MessageResourceWebMessageFailureTest.java, src/test/java/se/sundsvall/messaging/api/MessageResourceWebMessageTest.java
=> UF-11196: Change partyId to optional for webmessages

pom.xml, src/main/resources/integrations/web-message-sender-3.1.yml
=> UF-11196: Update web-message-sender api to 3.1

src/main/java/se/sundsvall/messaging/integration/digitalmailsender/DigitalMailSenderIntegrationConfiguration.java
=> uf-11397: Ignore 404 from DigitalMail

src/main/resources/application.yml
=> uf-11397: Ignore ClientProblem for Digital Mail

src/integration-test/java/apptest/MessagesIT.java, src/main/java/se/sundsvall/messaging/service/MessageEventHandler.java
=> Added request-id handling for async calls

src/integration-test/resources/LetterIT/__files/test2_withPartyId_withoutAddress_SNAIL_MAIL_attachment/mappings/snailmail-sender.json, src/integration-test/resources/LetterIT/__files/test6_withPartyId_withAddress_ANY_attachment/mappings/snailmail-sender.json, src/integration-test/resources/LetterIT/__files/test7_withPartyId_withAddress_ANY_attachment_and_failure_from_digital_mail/mappings/snailmail-sender.json, src/main/java/se/sundsvall/messaging/Constants.java, src/main/java/se/sundsvall/messaging/api/MessageResource.java, src/main/java/se/sundsvall/messaging/api/model/request/LetterRequest.java, src/main/java/se/sundsvall/messaging/api/model/request/SnailMailRequest.java, src/main/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailDto.java, src/main/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderClient.java, src/main/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderIntegration.java, src/main/java/se/sundsvall/messaging/service/mapper/DtoMapper.java, src/test/java/se/sundsvall/messaging/TestDataFactory.java, src/test/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailDtoTest.java, src/test/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderIntegrationTest.java, src/test/java/se/sundsvall/messaging/service/mapper/DtoMapperTest.java
=> uf-11764: Fix x-issuer and x-origin not being included towards snail mail

pom.xml, src/integration-test/resources/LetterIT/__files/test2_withPartyId_withoutAddress_SNAIL_MAIL_attachment/mappings/citizen.json, src/integration-test/resources/LetterIT/__files/test4_withPartyId_withoutAddress_SNAIL_MAIL_attachment_and_failure_from_citizen/mappings/citizen.json, src/integration-test/resources/LetterIT/__files/test7_withPartyId_withAddress_ANY_attachment_and_failure_from_digital_mail/mappings/citizen.json, src/main/java/se/sundsvall/messaging/integration/citizen/CitizenClient.java, src/main/java/se/sundsvall/messaging/integration/citizen/CitizenIntegration.java, src/main/java/se/sundsvall/messaging/service/MessageService.java, src/main/resources/integrations/citizen-v3.yml, src/test/java/se/sundsvall/messaging/integration/citizen/CitizenIntegrationTest.java, src/test/java/se/sundsvall/messaging/service/MessageServiceTest.java
=> UF-14662: Updated citizen integration to v3

src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/model/request/WebMessageRequest.java
=> UF-15120: increased mention of a file limit on webmessagerequest attachments

pom.xml, src/main/java/se/sundsvall/messaging/util/JsonUtils.java
=> UF-15118 Upping objectmappers streamread constraint

src/integration-test/java/apptest/HistoryIT.java, src/integration-test/resources/HistoryIT/__files/test9_messageMetadata/response.json, src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/Constants.java, src/main/java/se/sundsvall/messaging/api/HistoryResource.java, src/main/java/se/sundsvall/messaging/api/model/ApiMapper.java, src/test/java/se/sundsvall/messaging/TestDataFactory.java, src/test/java/se/sundsvall/messaging/api/HistoryResourceFailureTest.java, src/test/java/se/sundsvall/messaging/api/HistoryResourceTest.java, src/test/java/se/sundsvall/messaging/api/model/ApiMapperTest.java, src/test/java/se/sundsvall/messaging/api/model/HistoryMetadataTest.java
=> uf-15720: New resource for history without file-content

src/main/java/se/sundsvall/messaging/service/MessageService.java, src/main/java/se/sundsvall/messaging/service/mapper/DtoMapper.java, src/test/java/se/sundsvall/messaging/service/MessageServiceTest.java, src/test/java/se/sundsvall/messaging/service/mapper/DtoMapperTest.java
=> uf-16015: Fix missing address when sending async letter

src/main/resources/application.yml
* Updated circuitbreaker configuration, now ignores client problems from party.
=> UF-16322 Circuitbreaker configuration

src/integration-test/resources/LetterIT/__files/test2_withPartyId_withoutAddress_SNAIL_MAIL_attachment/mappings/snailmail-sender.json, src/integration-test/resources/LetterIT/__files/test6_withPartyId_withAddress_ANY_attachment/mappings/snailmail-sender.json, src/integration-test/resources/LetterIT/__files/test7_withPartyId_withAddress_ANY_attachment_and_failure_from_digital_mail/mappings/snailmail-sender.json, src/main/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderClient.java, src/main/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderIntegration.java, src/main/resources/integrations/snailmail-sender-3.0.yml, src/test/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderIntegrationTest.java
=> uf-16364: Remove x-issuer towards snail mail and update to 3.1.

src/main/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderClient.java, src/main/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderIntegration.java, src/test/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderIntegrationTest.java
=> uf-xyz: quick fix for reintroducing issuer towards snailmail

pom.xml, src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/model/ApiMapper.java, src/main/java/se/sundsvall/messaging/api/model/request/WebMessageRequest.java, src/test/java/se/sundsvall/messaging/api/MessageResourceWebMessageFailureTest.java, src/test/java/se/sundsvall/messaging/api/MessageResourceWebMessageTest.java
=> Uf 16423 bug empty list webmessage

src/integration-test/resources/WebMessageIT/__files/test1_successfulRequest/mappings/oep-integrator-createWebmessage.json, src/integration-test/resources/WebMessageIT/__files/test1_successfulRequest/request.json, src/main/java/se/sundsvall/messaging/integration/oepintegrator/OepIntegratorMapper.java, src/test/java/se/sundsvall/messaging/integration/oepintegrator/OepIntegratorMapperTest.java
=> UF-16429: Webmessages: mapping correction for sendAsOwner

src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/HistoryResource.java, src/main/java/se/sundsvall/messaging/integration/db/DbIntegration.java, src/main/java/se/sundsvall/messaging/integration/db/HistoryRepository.java, src/main/java/se/sundsvall/messaging/integration/db/mapper/HistoryMapper.java, src/main/java/se/sundsvall/messaging/integration/db/projection/BatchHistoryProjection.java, src/main/java/se/sundsvall/messaging/service/BatchExtractor.java, src/main/java/se/sundsvall/messaging/service/HistoryService.java, src/main/java/se/sundsvall/messaging/util/PagingUtil.java, src/test/java/se/sundsvall/messaging/api/HistoryResourceFailureTest.java, src/test/java/se/sundsvall/messaging/api/HistoryResourceTest.java, src/test/java/se/sundsvall/messaging/integration/db/DbIntegrationTest.java, src/test/java/se/sundsvall/messaging/integration/db/mapper/HistoryMapperTest.java, src/test/java/se/sundsvall/messaging/service/BatchExtractorTest.java, src/test/java/se/sundsvall/messaging/service/HistoryServiceAttachmentTest.java, src/test/java/se/sundsvall/messaging/service/HistoryServiceTest.java, src/test/java/se/sundsvall/messaging/util/PagingUtilTest.java
=> UF-16443: Implemented service logic for building batch history response

src/integration-test/resources/DigitalInvoiceIT/__files/test1_successfulRequest/mappings/digital-mail-sender.json, src/integration-test/resources/DigitalInvoiceIT/__files/test2_internalServerErrorFromDigitalMailSender/mappings/digital-mail-sender.json, src/integration-test/resources/DigitalInvoiceIT/__files/test3_invalidCertificateInDigitalMailSender/mappings/digital-mail-sender.json, src/integration-test/resources/DigitalMailIT/__files/test1_successfulRequest/mappings/digital-mail-sender.json, src/integration-test/resources/DigitalMailIT/__files/test2_internalServerErrorFromDigitalMailSender/mappings/digital-mail-sender.json, src/integration-test/resources/EmailIT/__files/test1_successfulRequest/mappings/email-sender.json, src/integration-test/resources/EmailIT/__files/test2_internalServerErrorFromEmailSender/mappings/email-sender.json, src/integration-test/resources/LetterIT/__files/test1_withPartyId_withoutAddress_DIGITAL_MAIL_attachment/mappings/digital-mail-sender.json, src/integration-test/resources/LetterIT/__files/test2_withPartyId_withoutAddress_SNAIL_MAIL_attachment/mappings/snailmail-sender-batch.json, src/integration-test/resources/LetterIT/__files/test2_withPartyId_withoutAddress_SNAIL_MAIL_attachment/mappings/snailmail-sender.json, src/integration-test/resources/LetterIT/__files/test3_withPartyId_withoutAddress_ANY_attachment/mappings/digital-mail-sender.json, src/integration-test/resources/LetterIT/__files/test6_withPartyId_withAddress_ANY_attachment/mappings/digital-mail-sender.json, src/integration-test/resources/LetterIT/__files/test6_withPartyId_withAddress_ANY_attachment/mappings/snailmail-sender-batch.json, src/integration-test/resources/LetterIT/__files/test6_withPartyId_withAddress_ANY_attachment/mappings/snailmail-sender.json, src/integration-test/resources/LetterIT/__files/test7_withPartyId_withAddress_ANY_attachment_and_failure_from_digital_mail/mappings/digital-mail-sender.json, src/integration-test/resources/LetterIT/__files/test7_withPartyId_withAddress_ANY_attachment_and_failure_from_digital_mail/mappings/snailmail-sender-batch.json, src/integration-test/resources/LetterIT/__files/test7_withPartyId_withAddress_ANY_attachment_and_failure_from_digital_mail/mappings/snailmail-sender.json, src/integration-test/resources/MessagesIT/__files/test1_successfulRequest_bySms/mappings/sms-sender.json, src/integration-test/resources/MessagesIT/__files/test2_successfulRequest_byEmail/mappings/email-sender.json, src/integration-test/resources/MessagesIT/__files/test5_successfulRequest_byBothSmsAndEmail/mappings/email-sender.json, src/integration-test/resources/MessagesIT/__files/test5_successfulRequest_byBothSmsAndEmail/mappings/sms-sender.json, src/integration-test/resources/SlackIT/__files/test1_successfulRequest/mappings/slack.postMessage.json, src/integration-test/resources/SlackIT/__files/test2_channelNotFoundErrorFromSlack/mappings/slack.postMessage.json, src/integration-test/resources/WebMessageIT/__files/test2_internalServerErrorFromWebMessageSender/mappings/oep-integrator-createWebmessage.json
=> UF-16028: Add bodyPatterns to integration tests

src/main/java/se/sundsvall/messaging/api/validation/impl/ValidWebMessageRequestConstraintValidator.java, src/test/java/se/sundsvall/messaging/api/validation/impl/ValidWebMessageRequestConstraintValidatorTest.java
=> UF-17015: Sender should be able to be null

src/main/java/se/sundsvall/messaging/api/interceptor/HeaderInterceptor.java, src/main/java/se/sundsvall/messaging/api/interceptor/InterceptorConfig.java, src/test/java/se/sundsvall/messaging/api/interceptor/HeaderInterceptorResourceTest.java, src/test/java/se/sundsvall/messaging/api/interceptor/HeaderInterceptorTest.java, src/test/java/se/sundsvall/messaging/api/interceptor/InterceptorConfigTest.java
=> hydran-260: Add interceptor for translating deprecated header.

pom.xml, src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/MessageResource.java, src/main/java/se/sundsvall/messaging/api/model/request/SnailMailRequest.java, src/main/java/se/sundsvall/messaging/service/MessageService.java, src/test/java/se/sundsvall/messaging/api/MessageResourceSnailMailBatchFailureTest.java, src/test/java/se/sundsvall/messaging/api/MessageResourceSnailMailBatchTest.java, src/test/java/se/sundsvall/messaging/api/MessageResourceSnailMailFailureTest.java, src/test/java/se/sundsvall/messaging/api/MessageResourceSnailMailTest.java, src/test/java/se/sundsvall/messaging/api/model/request/SnailMailRequestTest.java, src/test/java/se/sundsvall/messaging/service/MessageServiceTest.java
* Added new snailmail resources
=> HYDRAN-297 Snailmail resources

pom.xml, src/integration-test/resources/SnailMailIT/__files/test1_sendSnailMail_successfulRequest/mappings/snail-mail-sender.json, src/integration-test/resources/SnailMailIT/__files/test1_sendSnailMail_successfulRequest/request.json, src/integration-test/resources/openapi.yml, src/main/java/se/sundsvall/messaging/api/model/request/SnailMailRequest.java, src/main/java/se/sundsvall/messaging/api/validation/ValidFolderName.java, src/main/java/se/sundsvall/messaging/api/validation/impl/ValidFolderNameValidator.java, src/main/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailDto.java, src/main/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailSenderIntegrationMapper.java, src/main/java/se/sundsvall/messaging/service/mapper/DtoMapper.java, src/main/resources/integrations/email-sender-2.0.yml, src/main/resources/integrations/snailmail-sender-3.2.yml, src/test/java/se/sundsvall/messaging/TestDataFactory.java, src/test/java/se/sundsvall/messaging/api/MessageResourceSnailMailFailureTest.java, src/test/java/se/sundsvall/messaging/api/model/request/SnailMailRequestTest.java, src/test/java/se/sundsvall/messaging/api/validation/impl/ValidFolderNameValidatorTest.java, src/test/java/se/sundsvall/messaging/integration/snailmailsender/SnailMailDtoTest.java, src/test/java/se/sundsvall/messaging/service/mapper/DtoMapperTest.java
* Updated SnailmailSender integration to version 3.2. 
* Updated SnailMailRequest to include an optional folderName. 
* FolderName is passed along to SnailMailSender
* New minor version.
=> HYDRAN-369 Updated SnailMailSender Integration 

pom.xml, src/integration-test/resources/MessagesIT/__files/test1_successfulRequest_bySms/mappings/sms-sender.json, src/integration-test/resources/MessagesIT/__files/test1_successfulRequest_bySms/responses/contact-settings.json, src/integration-test/resources/MessagesIT/__files/test5_successfulRequest_byBothSmsAndEmail/mappings/sms-sender.json, src/integration-test/resources/MessagesIT/__files/test5_successfulRequest_byBothSmsAndEmail/responses/contact-settings.json, src/main/resources/integrations/contact-settings-2.0.yml, src/main/resources/integrations/sms-sender-2.0.yml, src/test/java/se/sundsvall/messaging/TestDataFactory.java, src/test/java/se/sundsvall/messaging/api/MessageResourceSmsBatchFailureTest.java, src/test/java/se/sundsvall/messaging/api/MessageResourceSmsFailureTest.java, src/test/java/se/sundsvall/messaging/service/MessageServiceTest.java
=> UF-17393: Change to a fake phone number in test/doc
